/**
 * @author Vikrant
 * @since 11-03-2023
 * @description to hold Admin dashboard permissions
 * @return {{ADD_AMENITY: string, DELETE_CE: string, ADD_USER_REMARKS: string, DELETE_AGENT: string, UPDATE_PROPERTY_AMENITY: string, VISIT_PROPERTY: string, UPDATE_PROPERTY: string, DELETE_PROPERTY_VARIANT: string, ADD_AGENT: string, ADD_DEVELOPER: string, UPDATE_DEVELOPER: string, DELETE_DEVELOPER: string, ADD_PROPERTY_VARIANT: string, UPDATE_AMENITY: string, UPDATE_PROFILE: string, BOOK_PROPERTY: string, ADD_LEAD: string, UPDATE_CUSTOMER_STATUS: string, ADD_PROPERTY: string, DELETE_USER: string, DELETE_PROPERTY_AMENITY: string, ADD_PROPERTY_AMENITY: string, ASSIGN_RM: string, DELETE_PROPERTY: string, ADD_RM: string, UPDATE_LEAD: string, UPDATE_AGENT: string, DELETE_RM: string, GET_BUILDER_STATISTICS: string}}
 */
const createPermissions = () => {
    const PERM_PREFIX = "MZ_PERM_";
    return {
        BOOK_PROPERTY: PERM_PREFIX + "0000001",
        VISIT_PROPERTY: PERM_PREFIX + "0000002",
        UPDATE_PROFILE: PERM_PREFIX + "0000003",
        ADD_RM: PERM_PREFIX + "0000004",
        ADD_AGENT: PERM_PREFIX + "0000005",
        ADD_DEVELOPER: PERM_PREFIX + "0000006",
        ADD_PROPERTY: PERM_PREFIX + "0000007",
        ADD_PROPERTY_VARIANT: PERM_PREFIX + "0000008",
        UPDATE_AGENT: PERM_PREFIX + "0000009",
        DELETE_AGENT: PERM_PREFIX + "0000010",
        ADD_AMENITY: PERM_PREFIX + "0000011",
        UPDATE_AMENITY: PERM_PREFIX + "0000012",
        ASSIGN_RM: PERM_PREFIX + "0000013",
        UPDATE_CUSTOMER_STATUS: PERM_PREFIX + "0000014",
        DELETE_CE: PERM_PREFIX + "0000015",
        DELETE_USER: PERM_PREFIX + "0000016",
        DELETE_RM: PERM_PREFIX + "0000017",
        DELETE_DEVELOPER: PERM_PREFIX + "0000018",
        DELETE_PROPERTY: PERM_PREFIX + "0000019",
        DELETE_PROPERTY_VARIANT: PERM_PREFIX + "0000020",
        ADD_LEAD: PERM_PREFIX + "0000021",
        UPDATE_LEAD: PERM_PREFIX + "0000022",
        UPDATE_DEVELOPER: PERM_PREFIX + "0000023",
        GET_BUILDER_STATISTICS: PERM_PREFIX + "0000024",
        ADD_PROPERTY_AMENITY: PERM_PREFIX + "0000025",
        UPDATE_PROPERTY_AMENITY: PERM_PREFIX + "0000026",
        UPDATE_PROPERTY: PERM_PREFIX + "0000027",
        DELETE_PROPERTY_AMENITY: PERM_PREFIX + "0000028",
        ADD_USER_REMARKS: PERM_PREFIX + "0000029",
    }
}

export const Permissions = createPermissions();
