import {useEffect, useState} from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/pages/home/header/Header';
import ServicesWrapper from '../components/pages/home/servicesWrapper/ServicesWrapper.jsx';
import ExclusivePropertiesCarousel
    from '../components/pages/home/exclusivePropertiesCarousel/ExclusivePropertiesCarousel';
import Footer from '../components/pages/home/footer/Footer';
import TopDevelopers from '../components/pages/home/topDevelopers/TopDevelopers';
import AssuredProperties from '../components/pages/home/assuredProperties/AssuredProperties';
import FastSellingProperties from '../components/pages/home/fastSellingProperties/FastSellingProperties';
import TopProperties from '../components/pages/home/topProperties/TopProperties.jsx';
import PropertiesMap from '../components/pages/home/propertiesMap/PropertiesMap';
import BlogsCarousel from '../components/pages/home/blogsCarousel/BlogsCarousel';
import {connect} from 'react-redux';
import {loadHomeScreenData} from '../actions/home';

function Home({homeReducer, loading, loadHomeScreenData}) {
    const [user, setUser] = useState([]);

    useEffect(() => {
        loadHomeScreenData();
        setUser(localStorage.getItem('user'));
    }, []);

    useEffect(() => {
        if (loading !== homeReducer.loading) {
            setUser(homeReducer.loading);
        }
    }, [homeReducer.loading]);

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Home</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link
                        rel="stylesheet"
                        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,1,0"
                    />
                </Head>
                <Header/>
                <ServicesWrapper/>
                <ExclusivePropertiesCarousel/>
                <TopDevelopers/>
                <AssuredProperties/>
                <FastSellingProperties/>
                <TopProperties/>
                <PropertiesMap/>
                <BlogsCarousel/>
                <Footer/>
            </div>
        </>
    );
}

const mapStateToProps = ({homeReducer}) => {
    return {
        homeReducer,
    };
};

const mapDispatchToProps = {
    loadHomeScreenData,
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
