/**
 * @author Lovesh Singh.
 * @since 12-01-2023.
 * @type {string} auth action types.
 */
export const CAN_PROCEED_FURTHER = 'CAN_PROCEED_FURTHER';
export const LOGGED_IN ="LOGGED_IN";
export const LOADING = 'LOADING';
export const MEETINGS_LOADING = 'MEETINGS_LOADING';
export const ERROR = 'ERROR';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const SET_SHORTLISTED_PROPERTIES = 'SET_SHORTLISTED_PROPERTIES'
export const SET_VIEWED_PROPERTIES_COUNT = 'SET_VIEWED_PROPERTIES_COUNT'
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST'
export const SET_VIEWED_PROPERTIES = 'SET_VIEWED_PROPERTIES'
export const SET_VISITED_PROPERTIES = 'SET_VISITED_PROPERTIES'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const UPDATE_USER_PROFILE = 'SET_USER_PROFILE'
export const UPDATE_MEETING = 'UPDATE_MEETING'
export const SET_VISITS = 'SET_VISITS'
export const SET_USER_BOOKED_PROPERTIES = 'SET_USER_BOOKED_PROPERTIES'
export const SET_USER_BOOKED_PROPERTIES_LOADING = 'SET_USER_BOOKED_PROPERTIES_LOADING'
export const SET_USER_MY_PROPERTIES = 'SET_USER_MY_PROPERTIES'
export const SET_ADMIN_METADATA = 'SET_ADMIN_METADATA'

