export const LOADING = 'LOADING [HOME]'
export const ERROR = 'ERROR'
export const SET_FAST_SELLING_PROPERTIES = 'SET_FAST_SELLING_PROPERTIES'
export const SET_ASSURED_PROPERTIES = 'SET_ASSURED_PROPERTIES'
export const SET_TOP_PROPERTIES = 'SET_TOP_PROPERTIES'
export const SET_TOP_DEVELOPERS = 'SET_TOP_DEVELOPERS'
export const SET_EXCLUSIVE_PROPERTIES = 'SET_EXCLUSIVE_PROPERTIES'
export const SET_TOP_DEVELOPER_PROPERTIES = 'SET_TOP_DEVELOPER_PROPERTIES'
export const SET_DEVELOPERS = 'SET_DEVELOPERS'
export const SET_ALL_PROPERTIES = 'SET_ALL_PROPERTIES'
export const SET_ALL_CITIES = 'SET_ALL_CITIES'
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA'


