export const NetworkConfiguration = {
    LOGOUT_API: "logout",
    LOGIN_API: "login",
    PROPERTIES_API: "filtered-properties",
    WISHLIST_API: "wishlist",
    TOP_DEVELOPER_API: "topDevelopers",
    DEVELOPER_PROPERTIES_API: "developer-properties",
    USER_PROFILE_API: "profile",
    PROPERTY_API: "propertyId",
    PROPERTY_VARIANTS_API: "propertyVariants",
    PROPERTY_VARIANT_API: "propertyVariant",
    PROPERTY_AMENITY_API: "amenity",
    DEVELOPER_API: "developer",
    FILTER_PROPERTIES_API: "filter-properties",
    USER_API: "user",
    VISIT_PROPERTY_API: "meeting",
    DEVELOPERS_API: "developers",
    ALL_PROPERTIES_API: "properties",
    VISITED_PROPERTY_API: "visited-property",
    VIEWED_PROPERTY_API: "viewed-property",
    USER_BOOKED_PROPERTY_API: "userBookedProperty",
    BOOKING_API: "booking",
    VISIT_BOOKING_API: "visitBooking",
    VIEW_PROPERTY_API: "viewProperty",
    RM_API: "rm",
    USER_REMARKS: "userRemarks",
    RMS_API: "rms",
    RM_Customer_API: "rmCustomer",
    Customers_API: "customers",
    BUILDERS_API: "builders",
    AGENTS_API: "agents",
    AGENT_API: "agent",
    LEAD_API: "lead",
    LEADS_API: "leads",
    DELETE_PROPERTY: "property",
    ASSIGN_RM_API: "assignRm",
    CUSTOMER_STATUS_API: "customerStatus",
    PAYMENT_STATUS_API: "payment",
    UPDATE_PROFILE_API: "updateProfile",
    BUILDER_STATS_API: "builderStats",
    PROPERTY_BOOKING_STAT_API: "propertyBookingStats",
    PROPERTY: "property",
    ADD_PROFILE_API: "add-profile",
    UPLOAD: "upload",
    CE_API:"ce",
    CONTACT: "contact",
    CAREER: "career",
    VIEWED_PROPERTIES_COUNT: "viewed-property-count",
    BOOKING: "booking",
    OFFLINE_BOOKING: "offlineBooking",
    // DEVELOPER_API:"developer",

    DOWNLOAD_PROPERTY_VARIANTS_API: "downloadPropertyVariants",
    DOWNLOAD_BUILDER_STATS_API: "downloadBuilderStat",
    DOWNLOAD_BUILDERS_API: "downloadBuilders",
    DOWNLOAD_AGENT_LEADS_API: "downloadAgentLeads",
    DOWNLOAD_CUSTOMERS_LIST_API: "downloadCustomers",
    DOWNLOAD_PROPERTY_BOOKINGS_API: "downloadPropertyBookings",
    DOWNLOAD_CUSTOMER_DASHBOARD_API: "downloadCustomerDashboard",
    DOWNLOAD_BUILDER_SALES_API: "downloadBuilderSales",
    DOWNLOAD_BUILDER_SALES_UNIT_API: "downloadBuilderSalesUnit",
    DOWNLOAD_TOTAL_SALES_API: "downloadTotalSales",
    DOWNLOAD_RM_CUSTOMER_API: "downloadRmCustomer",
    DOWNLOAD_RMS_API: "downloadRms",
    DOWNLOAD_ADMIN_LEADS_API: "downloadAdminLeads",
    DOWNLOAD_CE_LIST_API: "downloadCustomerExperienceTeam",
    DOWNLOAD_CONTRACTED_AGENTS_API: "downloadContractedAgents",
    AMENITIES_API: "amenities",
    PROPERTY_AMENITIES_API: "propertyId-amenity",

    EMAIL_LOGIN_SIGNUP: "emailLoginSignup",
    EMAIL_SIGNUP: "emailSignup",
    VERIFY_EMAIL_SIGNUP: "emailSignupLogin",
    VERIFY_EMAIL_LOGIN: "emailLogin",

    MOBILE_LOGIN_SIGNUP: "mobileLoginSignup",
    MOBILE_SIGNUP: "mobileSignup",
    VERIFY_MOBILE_SIGNUP: "mobileSignupLogin",
    VERIFY_MOBILE_LOGIN: "mobileLogin",
    PROPERTY_VARIANT_BY_ID: "propertyVariantById",
    BOOKING_PAYMENT_OFFLINE: "BookingOfflinePayment",
    CITY:"city",
    STATE:"state",
    AREA:"area",
    PAYMENTS:"payments",
    ALL_CITIES_API: "cities",
    KEYWORD_SEARCH_API: "keyword"
}
